import type { NextPage } from 'next'
import Head from 'next/head'
import About from './about'
import Navbar from './components/Navbar'

const Home: NextPage = () => {
  return (
    <div className='bg-home bg-no-repeat bg-cover min-h-screen'>
      <Head>
        <title>Sara Holm Pedersen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className='text-brown font-bold flex flex-col justify-center items-center h-screen px-6 text-center'>
        <h1 className='text-3xl md:text-6xl'>Sara Holm Pedersen</h1>
        <p>Informatics student at the</p>
        <p>Norwegian University of Science and Technology</p>
      </div>
    </div>
  )
}

export default Home